[package]
name = "vors_common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
<<<<<<< HEAD:src/share_common/Cargo.toml
backtrace = "0.3"
glam = { version = "0.24", features = ["serde"] }
=======
glam = { version = "0.22", features = ["serde"] }
>>>>>>> develop:src/common/Cargo.toml
log = "0.4"
once_cell = "1"
parking_lot = "0.12"
semver = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
<<<<<<< HEAD:src/share_common/Cargo.toml
settings-schema = { git = "https://github.com/zarik5/settings-schema-rs" }
# settings-schema = { path = "../../../../settings-schema-rs/settings-schema" }

[target.'cfg(windows)'.dependencies]
msgbox = "0.7"

=======

[target.'cfg(windows)'.dependencies]
msgbox = "0.7"
>>>>>>> develop:src/common/Cargo.toml
